# Note: Since the introduction of workspaces we recommend using workspaces instead of using this file to inform apiops about extracting select artifacts instead of extracting everything. 
# We are keeping support for this file as not everyone will be able to use workspaces.
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview

 apiNames:
  - api1
  - api2

 backendNames:
  - backend1
  - backend2

 diagnosticNames:
 - diagnostic1
 - diagnostic2

 loggerNames:
  - loggerName1
  - loggerName2

 namedValueNames:
  - namedValueName1
  - namedValueName2

 productNames:
  - productName2
  - productName2

 subscriptionNames:
 - subscription1
 - subscription2

 tagNames:
  - tag1
  - tag2