# This is a basic workflow to help you get started with Actions

name: Run Extractor

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  AZURE_RESOURCE_GROUP_NAME: your-apim-resourceGroupName  # Replace this value with your resource group name
  API_MANAGEMENT_SERVICE_NAME: your-apim-instanceName  # Replace this value with yourapim instance name 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  extract:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-extractor.yml
          name: extractor
          
      - name: Run extractor
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ env.API_MANAGEMENT_SERVICE_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/artifacts
        run: |
          chmod +x ./extractor
          ./extractor
          ls -la ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}
      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-from-portal
          path: ${{ GITHUB.WORKSPACE }}/artifacts     
          
  create-pull-request:
    needs: extract
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
          
      - name: Download artifacts-from-portal
        uses: actions/download-artifact@v2
        with:
          name: artifacts-from-portal
          path: "."

      - name: Create artifacts pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "updated extract from apim instance ${{ env.API_MANAGEMENT_SERVICE_NAME }}"
          title: "${{ env.API_MANAGEMENT_SERVICE_NAME }} - extract"
          body: >
            This PR is auto-generated by Github actions workflow
          labels: extract, automated pr